[package]
name = "push2run"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttc = "*"
json = "*"
toml = "*"
log = "*"
flexi_logger = { version = "*", features = ["colors"] }

